# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2fa57c4b682a7bb80db4e5229b2fbeffee15df56266303d2306682b9425557461d692efa3deb43734ea00c27229bbd8ad248dc6e330c9db61ff9a3669a6d737

test:
  secret_key_base: 00e1019950c8adf9428f4d8c7e61e2e6720311450540b2746a50c394b4e17bae7396f3f9abacf9ce580324ac84f1ef504b25f9230134fba3c136a1370da2bcac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
